version: "3.8"

services:
  mysql:
    image: mysql:lts
    container_name: lab6-mysql-container
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: "WaterLab@6"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
